import { InventoryItem, Blueprint, Quest, Achievement, SurvivalStage, SurvivalStageId, ItemRarity } from '../types';

export const RARITY_COLORS: Record<string, { bg: string; text: string; border: string; glow: string; label: string }> = {
  common: { bg: 'bg-zinc-700', text: 'text-zinc-200', border: 'border-zinc-500', glow: 'shadow-zinc-500/20', label: 'Bình thường' },
  good: { bg: 'bg-emerald-950', text: 'text-emerald-300', border: 'border-emerald-500', glow: 'shadow-emerald-500/30', label: 'Tốt' },
  superior: { bg: 'bg-sky-950', text: 'text-sky-300', border: 'border-sky-500', glow: 'shadow-sky-500/40', label: 'Ưu tú' },
  perfect: { bg: 'bg-purple-950', text: 'text-purple-300', border: 'border-purple-500', glow: 'shadow-purple-500/50', label: 'Hoàn hảo' },
  epic: { bg: 'bg-amber-950', text: 'text-amber-300', border: 'border-amber-500', glow: 'shadow-amber-500/60', label: 'Sử thi' },
  brilliant: { bg: 'bg-rose-950', text: 'text-rose-300', border: 'border-rose-400', glow: 'shadow-rose-500/70', label: 'Rực rỡ' },
};

export const INITIAL_ITEMS: InventoryItem[] = [
  {
    id: 'stone',
    name: 'Viên đá',
    category: 'weapon',
    rarity: 'common',
    quantity: 15,
    description: 'Đá nhặt ven đường, có thể dùng ném thăm dò hoặc tấn công thú nhỏ.',
    icon: '🪨',
    stats: { damage: 12 },
  },
  {
    id: 'bread',
    name: 'Bánh mì',
    category: 'consumable',
    rarity: 'common',
    quantity: 3,
    description: 'Thức ăn cơ bản ban đầu, hồi 25 độ đói.',
    icon: '🍞',
    stats: { hungerValue: 25 },
  },
  {
    id: 'purified_water_500ml',
    name: 'Nước tinh khiết 500ml',
    category: 'consumable',
    rarity: 'common',
    quantity: 4,
    description: 'Nước uống sạch giúp giải khát và làm mát cơ thể.',
    icon: '💧',
    stats: { waterValue: 30, tempMod: -0.5 },
  },
  {
    id: 'wood',
    name: 'Khối gỗ tiêu chuẩn',
    category: 'material',
    rarity: 'common',
    quantity: 16,
    description: 'Gỗ tiêu chuẩn dùng rèn giấy vệ sinh, que nướng, tủ bàn và phụ tùng.',
    icon: '🪵',
  },
  {
    id: 'iron_plate',
    name: 'Tấm sắt',
    category: 'material',
    rarity: 'common',
    quantity: 12,
    description: 'Kim loại cơ bản cho khung xe, bàn rèn và vũ khí.',
    icon: '🔩',
  },
  {
    id: 'rubber',
    name: 'Miếng cao su',
    category: 'material',
    rarity: 'common',
    quantity: 8,
    description: 'Cao su chế tạo lốp xe, gioăng bồn nước và chai nhựa.',
    icon: '⬛',
  },
  {
    id: 'seed_wheat',
    name: 'Hạt giống lúa mì sa mạc',
    category: 'material',
    rarity: 'common',
    quantity: 4,
    description: 'Hạt giống chịu hạn, có thể gieo trồng trong khoang Thủy Canh Nông Trại RV.',
    icon: '🌱',
  },
  {
    id: 'seed_cotton',
    name: 'Hạt giống cây bông',
    category: 'material',
    rarity: 'good',
    quantity: 2,
    description: 'Dùng gieo trồng thu hoạch bông sợi tự nhiên may áo giáp chống đạn.',
    icon: '🌾',
  },
];

export const INITIAL_BLUEPRINTS: Blueprint[] = [
  // --- BASIC CRAFTS ---
  {
    id: 'bp_toilet_paper',
    name: 'Giấy vệ sinh',
    rarity: 'common',
    resultItemId: 'toilet_paper',
    resultQuantity: 3,
    ingredients: [{ itemId: 'wood', quantity: 1 }],
    learned: true,
    description: 'Vật phẩm sinh tồn quốc dân! Dân thành phố xuyên không cực kỳ khao khát, là tiền tệ trao đổi thần thánh.',
    category: 'basic',
    sourceHint: 'Đã mở khóa mặc định',
  },
  {
    id: 'bp_plastic_bottle',
    name: 'Chai nhựa chứa nước 1L',
    rarity: 'common',
    resultItemId: 'plastic_bottle',
    resultQuantity: 2,
    ingredients: [{ itemId: 'rubber', quantity: 1 }],
    learned: true,
    description: 'Chai nhựa dùng hứng nước ngưng tụ sạch từ máy lọc trên nóc xe.',
    category: 'basic',
    sourceHint: 'Đã mở khóa mặc định',
  },
  {
    id: 'bp_bbq_skewer',
    name: 'Xiên thịt nướng sa mạc',
    rarity: 'common',
    resultItemId: 'bbq_meat',
    resultQuantity: 2,
    ingredients: [
      { itemId: 'wood', quantity: 1 },
      { itemId: 'salt', quantity: 1 },
    ],
    learned: true,
    description: 'Thịt dã thú ướp muối nướng than hoa, hồi phục 40 độ đói và tăng sinh lực.',
    category: 'basic',
    sourceHint: 'Đã mở khóa mặc định',
  },

  // --- WEAPONS & ARMOR ---
  {
    id: 'bp_wooden_spear',
    name: 'Giáo gỗ dài 2m',
    rarity: 'common',
    resultItemId: 'wooden_spear',
    resultQuantity: 1,
    ingredients: [{ itemId: 'wood', quantity: 2 }],
    learned: true,
    description: 'Vũ khí cận chiến tầm xa tiết kiệm đạn khi đối đầu thú hoang núp bụi.',
    category: 'weapon',
    sourceHint: 'Đã mở khóa mặc định',
  },
  {
    id: 'bp_steel_dagger',
    name: 'Dao găm thép',
    rarity: 'good',
    resultItemId: 'steel_dagger',
    resultQuantity: 1,
    ingredients: [
      { itemId: 'iron_plate', quantity: 12 },
      { itemId: 'wood', quantity: 2 },
    ],
    learned: false,
    description: 'Dao găm thép sắc bén dùng cắt thịt, xẻ da dã thú và tự vệ cận chiến cực nhanh.',
    category: 'weapon',
    sourceHint: 'Túi đồ khởi đầu / Rương Gỗ KM 1+',
  },
  {
    id: 'bp_reinforced_crossbow',
    name: 'Nỏ săn cánh đôi tầm xa',
    rarity: 'superior',
    resultItemId: 'reinforced_crossbow',
    resultQuantity: 1,
    ingredients: [
      { itemId: 'iron_plate', quantity: 20 },
      { itemId: 'wood', quantity: 8 },
      { itemId: 'rubber', quantity: 5 },
    ],
    learned: false,
    description: 'Nỏ trợ lực bắn êm không gây tiếng động, uy lực xuyên thủng da báo hoa sa mạc.',
    category: 'weapon',
    sourceHint: 'Rương Ưu Tú KM 3+ / Nhiệm vụ Cốt truyện Chương 2',
  },
  {
    id: 'bp_tang_dao',
    name: 'Đao Đường (Bách Luyện Hoàn Hảo)',
    rarity: 'perfect',
    resultItemId: 'tang_dao',
    resultQuantity: 1,
    ingredients: [
      { itemId: 'diamond', quantity: 1 },
      { itemId: 'iron_plate', quantity: 30 },
      { itemId: 'wood', quantity: 5 },
    ],
    learned: false,
    description: 'Đao Đường rèn trăm lần sắc bén chém sắt như chém bùn, một nhát chém đôi mãnh thú hung tợn.',
    category: 'weapon',
    sourceHint: 'Rương Hoàn Hảo KM 5+ / Nhiệm vụ Thợ Săn Sa Mạc',
  },
  {
    id: 'bp_desert_eagle',
    name: 'Súng lục Desert Eagle Bạo Kích',
    rarity: 'brilliant',
    resultItemId: 'desert_eagle',
    resultQuantity: 1,
    ingredients: [
      { itemId: 'diamond', quantity: 1 },
      { itemId: 'iron_plate', quantity: 25 },
      { itemId: 'copper_plate', quantity: 12 },
      { itemId: 'wood', quantity: 6 },
    ],
    learned: false,
    description: 'Khẩu súng lục thần thánh 30 viên đạn, giảm 90% độ giật, sát thương 1 phát bắn hạ gục sư tử sa mạc!',
    category: 'weapon',
    sourceHint: 'Rương Rực Rỡ KM 10+ / Đổi với Tinh Thần',
  },
  {
    id: 'bp_hunting_rifle',
    name: 'Súng trường bắn tỉa sa mạc',
    rarity: 'epic',
    resultItemId: 'hunting_rifle',
    resultQuantity: 1,
    ingredients: [
      { itemId: 'diamond', quantity: 2 },
      { itemId: 'iron_plate', quantity: 45 },
      { itemId: 'copper_plate', quantity: 20 },
      { itemId: 'wood', quantity: 10 },
    ],
    learned: false,
    description: 'Súng trường tầm xa có ống ngắm nhiệt, hạ gục toán cướp Phi Ca từ khoảng cách 800m.',
    category: 'weapon',
    sourceHint: 'Rương Sử Thi KM 15+ / Tiêu diệt Trùm Cướp Đường',
  },
  {
    id: 'bp_ammo_ap',
    name: 'Đạn xuyên giáp AP (100 viên)',
    rarity: 'superior',
    resultItemId: 'ammo_ap',
    resultQuantity: 100,
    ingredients: [
      { itemId: 'gunpowder', quantity: 10 },
      { itemId: 'copper_plate', quantity: 15 },
      { itemId: 'iron_plate', quantity: 10 },
    ],
    learned: false,
    description: 'Đạn xuyên giáp sơ tốc cao dùng cho Desert Eagle và súng trường, phá giáp kim loại tức thì.',
    category: 'weapon',
    sourceHint: 'Rương Ưu Tú KM 4+ / Trạm tiếp tế',
  },
  {
    id: 'bp_kevlar_vest',
    name: 'Áo giáp sợi Kevlar chống đạn',
    rarity: 'perfect',
    resultItemId: 'kevlar_vest',
    resultQuantity: 1,
    ingredients: [
      { itemId: 'cotton', quantity: 15 },
      { itemId: 'iron_plate', quantity: 25 },
      { itemId: 'rubber', quantity: 10 },
    ],
    learned: false,
    description: 'Áo giáp nhẹ giảm 85% sát thương từ đạn của bọn cướp đường và móng vuốt gấu đen.',
    category: 'weapon',
    sourceHint: 'Rương Hoàn Hảo KM 8+',
  },

  // --- SURVIVAL & LIFE ---
  {
    id: 'bp_water_purifier',
    name: 'Máy lọc nước ngưng tụ không khí',
    rarity: 'superior',
    resultItemId: 'water_purifier',
    resultQuantity: 1,
    ingredients: [
      { itemId: 'iron_plate', quantity: 10 },
      { itemId: 'copper_plate', quantity: 5 },
      { itemId: 'rubber', quantity: 4 },
    ],
    learned: false,
    description: 'Lắp trên nóc xe, tự động hút ẩm sa mạc và ngưng tụ 50L - 200L nước tinh khiết mỗi ngày.',
    category: 'survival',
    sourceHint: 'Rương Ưu Tú KM 2+ / Nhiệm Vụ Khát Khao Nguồn Nước',
  },
  {
    id: 'bp_car_fridge',
    name: 'Tủ lạnh xe hơi 3 ngăn cấp đông',
    rarity: 'perfect',
    resultItemId: 'car_fridge',
    resultQuantity: 1,
    ingredients: [
      { itemId: 'iron_plate', quantity: 30 },
      { itemId: 'copper_plate', quantity: 15 },
      { itemId: 'wood', quantity: 10 },
    ],
    learned: false,
    description: 'Bảo quản thực phẩm vĩnh viễn không ôi thiu, làm đá lạnh giải khát và làm lạnh bơ kem.',
    category: 'survival',
    sourceHint: 'Rương Hoàn Hảo KM 6+ / Thưởng Nhiệm Vụ Ẩn',
  },
  {
    id: 'bp_aphrodisiac_pill',
    name: 'Viên thuốc Thất Tình Lục Dục',
    rarity: 'perfect',
    resultItemId: 'aphrodisiac_pill',
    resultQuantity: 10,
    ingredients: [
      { itemId: 'wild_fruit', quantity: 5 },
      { itemId: 'toilet_paper', quantity: 5 },
    ],
    learned: false,
    description: 'Thuốc bí truyền cực mạnh! Pha loãng ném ra làm mồi nhử khiến bầy thú tự hỗn chiến và kiệt sức!',
    category: 'survival',
    sourceHint: 'Rương Ẩn Ven Rừng Sa Mạc / Đổi với Tinh Thần',
  },
  {
    id: 'bp_focus_cigarette',
    name: 'Thuốc lá Tụ Thần Tuyết Mộc',
    rarity: 'perfect',
    resultItemId: 'focus_cigarette',
    resultQuantity: 20,
    ingredients: [
      { itemId: 'wood', quantity: 2 },
      { itemId: 'cotton', quantity: 2 },
    ],
    learned: false,
    description: 'Tăng vĩnh viễn chỉ số Tinh Thần, xua tan mệt mỏi, giúp duy trì bình tĩnh trước bão cát và hiểm nguy.',
    category: 'luxury',
    sourceHint: 'Rương Hoàn Hảo KM 7+ / Đổi trên Kênh Thế Giới',
  },
  {
    id: 'bp_medical_kit',
    name: 'Túi cứu thương dã chiến cao cấp',
    rarity: 'good',
    resultItemId: 'medical_kit',
    resultQuantity: 3,
    ingredients: [
      { itemId: 'cotton', quantity: 5 },
      { itemId: 'purified_water_500ml', quantity: 2 },
      { itemId: 'toilet_paper', quantity: 4 },
    ],
    learned: false,
    description: 'Hồi phục ngay lập tức 80 HP, chữa lành vết cào xé nhiễm độc và băng bó gãy xương.',
    category: 'survival',
    sourceHint: 'Trạm Tiếp Tế / Rương Tốt KM 2+',
  },
  {
    id: 'bp_storage_ring',
    name: 'Nhẫn Trữ Vật Không Gian (100m³)',
    rarity: 'epic',
    resultItemId: 'storage_ring',
    resultQuantity: 1,
    ingredients: [
      { itemId: 'space_crystal', quantity: 1 },
      { itemId: 'iron_plate', quantity: 15 },
    ],
    learned: false,
    description: 'Bảo bối không gian liên kết linh hồn, chứa cả xe và hàng ngàn tấn hàng hóa mà không tốn diện tích!',
    category: 'survival',
    sourceHint: 'Rương Sử Thi KM 12+ / Nhiệm vụ Nhẫn Không Gian',
  },

  // --- VEHICLE & AMENITIES ---
  {
    id: 'bp_car_tires',
    name: 'Lốp gai chống đinh sa mạc',
    rarity: 'good',
    resultItemId: 'car_tires',
    resultQuantity: 4,
    ingredients: [
      { itemId: 'iron_plate', quantity: 20 },
      { itemId: 'rubber', quantity: 15 },
    ],
    learned: false,
    description: 'Lốp xe van cường hóa chống nổ khi chạy trên đá nhọn sa mạc, tăng tốc độ lên 50 km/h.',
    category: 'vehicle',
    sourceHint: 'Rương Tốt KM 1.5+ / Nhiệm vụ Lên Đời Bánh Xe',
  },
  {
    id: 'bp_car_engine',
    name: 'Động cơ V8 tăng áp cấp Ưu Tú',
    rarity: 'superior',
    resultItemId: 'car_engine',
    resultQuantity: 1,
    ingredients: [
      { itemId: 'iron_plate', quantity: 40 },
      { itemId: 'copper_plate', quantity: 15 },
      { itemId: 'rubber', quantity: 10 },
    ],
    learned: false,
    description: 'Động cơ êm ái, bốc mạnh, nâng tốc độ xe lên 80-100 km/h giúp thoát khỏi đàn sói sa mạc truy đuổi.',
    category: 'vehicle',
    sourceHint: 'Rương Ưu Tú KM 4+ / Nhiệm vụ Trái Tim Cơ Khí',
  },
  {
    id: 'bp_car_transmission',
    name: 'Hộp số 8 cấp siêu tiết kiệm xăng',
    rarity: 'superior',
    resultItemId: 'car_transmission',
    resultQuantity: 1,
    ingredients: [
      { itemId: 'iron_plate', quantity: 35 },
      { itemId: 'copper_plate', quantity: 10 },
    ],
    learned: false,
    description: 'Tối ưu hóa tỉ số truyền, giảm mức tiêu hao xăng xuống chỉ còn 3L/100km!',
    category: 'vehicle',
    sourceHint: 'Rương Ưu Tú KM 5+',
  },
  {
    id: 'bp_car_ac',
    name: 'Điều hòa Inverter âm trần',
    rarity: 'superior',
    resultItemId: 'car_ac',
    resultQuantity: 1,
    ingredients: [
      { itemId: 'iron_plate', quantity: 25 },
      { itemId: 'copper_plate', quantity: 10 },
      { itemId: 'rubber', quantity: 5 },
    ],
    learned: false,
    description: 'Hạ nhiệt cabin xe xuống 22°C cực kỳ mát mẻ, biến xe thành thiên đường giữa sa mạc 65°C.',
    category: 'vehicle',
    sourceHint: 'Rương Ưu Tú KM 3+ / Nhiệm vụ Vượt Qua Nắng Nóng Cực Độ',
  },
  {
    id: 'bp_roof_water_tank',
    name: 'Bồn nước nóc xe 1000L tự điều nhiệt',
    rarity: 'perfect',
    resultItemId: 'roof_water_tank',
    resultQuantity: 1,
    ingredients: [
      { itemId: 'iron_plate', quantity: 50 },
      { itemId: 'rubber', quantity: 20 },
      { itemId: 'wood', quantity: 10 },
    ],
    learned: false,
    description: 'Bồn nước dung tích khủng 1000L, tự đun nóng nước tắm 40°C hoặc làm lạnh 5°C tùy thích.',
    category: 'vehicle',
    sourceHint: 'Rương Hoàn Hảo KM 7+ / Nhiệm vụ Bồn Nước Thiên Đường',
  },
  {
    id: 'bp_bulletproof_glass',
    name: 'Kính chống đạn xe hơi đa lớp',
    rarity: 'superior',
    resultItemId: 'bulletproof_glass',
    resultQuantity: 1,
    ingredients: [
      { itemId: 'glass_shard', quantity: 20 },
      { itemId: 'iron_plate', quantity: 10 },
    ],
    learned: false,
    description: 'Chặn đứng sát thương đạn súng và móng vuốt quái thú khi đang lái xe trên đường.',
    category: 'vehicle',
    sourceHint: 'Rương Ưu Tú KM 6+',
  },
  {
    id: 'bp_ice_cream_maker',
    name: 'Máy làm kem bơ tuyết mát lạnh',
    rarity: 'brilliant',
    resultItemId: 'ice_cream_maker',
    resultQuantity: 1,
    ingredients: [
      { itemId: 'diamond', quantity: 1 },
      { itemId: 'iron_plate', quantity: 25 },
      { itemId: 'copper_plate', quantity: 10 },
      { itemId: 'wood', quantity: 5 },
    ],
    learned: false,
    description: 'Tạo ra những ly kem bơ tuyết mát lạnh, thơm ngon số 1 cao tốc, hồi phục 100% tinh thần.',
    category: 'luxury',
    sourceHint: 'Rương Rực Rỡ KM 10+ / Nhiệm vụ Trùm Kem Sa Mạc',
  },
  {
    id: 'bp_radar_scanner',
    name: 'Hệ thống Radar quét rương 1000M',
    rarity: 'perfect',
    resultItemId: 'radar_scanner',
    resultQuantity: 1,
    ingredients: [
      { itemId: 'copper_plate', quantity: 20 },
      { itemId: 'iron_plate', quantity: 30 },
      { itemId: 'diamond', quantity: 1 },
    ],
    learned: false,
    description: 'Mở rộng tầm quét của xe lên 1000 mét, phát hiện chính xác mọi rương ẩn và dã thú ven đường.',
    category: 'vehicle',
    sourceHint: 'Rương Hoàn Hảo KM 9+',
  },
];

export const SURVIVAL_STAGES: SurvivalStage[] = [
  {
    id: 'stage1_wasteland',
    name: 'Giai Đoạn 1: Hoang Mạc Vô Tận',
    dayNumber: 1,
    ambientTemp: 32,
    weatherCondition: 'Hoang mạc vô tận',
    description: 'Khởi đầu sinh tồn chỉ với xe van cũ nát. Tìm kiếm rương tài nguyên, chế tạo giấy vệ sinh đổi vật tư.',
    dangerLevel: 1,
    roadDifficulty: 1,
    activeSurvivingPlayers: 10000,
    minKm: 0,
    unlockedBonus: 'Mở khóa Bàn Rèn Cơ Bản & Thiên Phú 10 Phát Nhập Hồn',
  },
  {
    id: 'stage2_extreme_heat',
    name: 'Giai Đoạn 2: Nắng Nóng Cực Độ (45°C - 65°C)',
    dayNumber: 3,
    ambientTemp: 60,
    weatherCondition: 'Nắng nóng cực độ (45°C - 65°C)',
    description: 'Nhiệt độ ngoài trời tăng chóng mặt lên đến 65°C. Cần điều hòa xe, máy ngưng tụ nước, làm đá lạnh và kem bơ!',
    dangerLevel: 3,
    roadDifficulty: 2,
    activeSurvivingPlayers: 4567,
    minKm: 20,
    unlockedBonus: 'Mở khóa Máy Ngưng Tụ Nước & Khoang Thủy Canh Nông Trại RV',
  },
  {
    id: 'stage3_crossroads_bandits',
    name: 'Giai Đoạn 3: Ngã Rẽ Hiểm Nguy & Cướp Đường',
    dayNumber: 6,
    ambientTemp: 45,
    weatherCondition: 'Ngã rẽ sa mạc & cướp đường',
    description: 'Các nhóm cướp có vũ khí (Phi ca, Tiểu Phi) chặn đường trạm tiếp tế. Nâng cấp Xe Nhà RV và dùng súng lục dẹp loạn.',
    dangerLevel: 4,
    roadDifficulty: 3,
    activeSurvivingPlayers: 2156,
    minKm: 50,
    unlockedBonus: 'Mở khóa Đột Phá Pháo Đài RV & Súng Lục Desert Eagle',
  },
  {
    id: 'stage4_nightmare_spirits',
    name: 'Giai Đoạn 4: Đêm Đen & Quỷ Dị Hoang Tàn',
    dayNumber: 10,
    ambientTemp: 18,
    weatherCondition: 'Đêm đen quỷ dị & Bão cát',
    description: 'Màn đêm tăm tối xuất hiện ma thú kỳ dị. Bắn đạn mặt nạ rực rỡ và sát cánh cùng Chó Vàng Trung Hoa bảo vệ xe!',
    dangerLevel: 5,
    roadDifficulty: 4,
    activeSurvivingPlayers: 980,
    minKm: 100,
    unlockedBonus: 'Mở khóa Tiến Hóa Thiết Giáp Khuyển & Nhẫn Trữ Vật Không Gian',
  },
  {
    id: 'stage5_eternal_frost',
    name: 'Giai Đoạn 5: Bão Tuyết & Băng Giá Vĩnh Cửu (-35°C)',
    dayNumber: 15,
    ambientTemp: -35,
    weatherCondition: 'Bão tuyết & Băng giá vĩnh cửu (-35°C)',
    description: 'Băng giá bao trùm mặt đường cao tốc. Động cơ cần sưởi ấm, lốp xích tuyết chống trượt, bồn nước giữ nhiệt 40°C.',
    dangerLevel: 6,
    roadDifficulty: 5,
    activeSurvivingPlayers: 480,
    minKm: 200,
    unlockedBonus: 'Mở khóa Lò Sưởi Nhiệt Năng & Cây Trồng Dưa Lưới Tuyết Băng',
  },
  {
    id: 'stage6_radiation_zone',
    name: 'Giai Đoạn 6: Rừng Phóng Xạ & Quái Dị Đột Biến',
    dayNumber: 22,
    ambientTemp: 25,
    weatherCondition: 'Rừng phóng xạ & Quái dị đột biến',
    description: 'Bụi phóng xạ bao phủ xa lộ, dã thú đột biến kích thước khổng lồ cấp Titan. Trang bị Giáp Chì và Đạn Plasma!',
    dangerLevel: 7,
    roadDifficulty: 6,
    activeSurvivingPlayers: 195,
    minKm: 350,
    unlockedBonus: 'Mở khóa Đột Phá Xe Hạt Nhân Cyberpunk & Thần Khuyển Lôi Điện',
  },
  {
    id: 'stage7_infernal_abyss',
    name: 'Giai Đoạn 7: Vực Thẳm Dung Nham & Hỏa Ngục',
    dayNumber: 30,
    ambientTemp: 78,
    weatherCondition: 'Vực thẳm dung nham & Hỏa ngục',
    description: 'Mặt đường nứt nẻ nham thạch nóng chảy ngàn độ. Bão lửa cuồng phong thử thách lòng dũng cảm của người xuyên không.',
    dangerLevel: 8,
    roadDifficulty: 7,
    activeSurvivingPlayers: 64,
    minKm: 550,
    unlockedBonus: 'Mở khóa Lá Chắn Từ Trường & Tháp Pháo Nóc Xe Tự Động',
  },
  {
    id: 'stage8_cosmic_elevator',
    name: 'Giai Đoạn 8: Thang Máy Không Gian Tối Thượng',
    dayNumber: 45,
    ambientTemp: 20,
    weatherCondition: 'Thang máy không gian tối thượng',
    description: 'Điểm đến huyền thoại của trò chơi sinh tồn xuyên không. Thang máy đưa xe bay lơ lửng tiến vào trạm vũ trụ tinh vân!',
    dangerLevel: 9,
    roadDifficulty: 8,
    activeSurvivingPlayers: 12,
    minKm: 800,
    unlockedBonus: 'Mở khóa Tàu Bay Không Gian & Danh Hiệu Thần Thoại Vô Tận',
  },
];

// 7 CẢNH GIỚI TRƯỞNG THÀNH SINH TỒN
export const SURVIVOR_REALMS: { [level: number]: {
  level: number;
  name: string;
  title: string;
  icon: string;
  color: string;
  badgeBorder: string;
  requiredKm: number;
  requiredKills: number;
  requiredChests: number;
  requiredBadges: number;
  passives: string[];
  hpBonus: number;
  critRateBonus: number;
  speedBonus: number;
  craftCritBonus: number;
} } = {
  1: {
    level: 1,
    name: 'Tân Binh Xuyên Không',
    title: 'Người Mới Đến Xa Lộ',
    icon: '🌱',
    color: 'text-zinc-300',
    badgeBorder: 'border-zinc-500',
    requiredKm: 0,
    requiredKills: 0,
    requiredChests: 0,
    requiredBadges: 0,
    passives: ['Cơ bản: Tốc độ di chuyển cơ bản', 'Bàn rèn: Kích hoạt thiên phú 10 Phát Nhập Hồn'],
    hpBonus: 0,
    critRateBonus: 0,
    speedBonus: 0,
    craftCritBonus: 0,
  },
  2: {
    level: 2,
    name: 'Kẻ Lang Bạt Sa Mạc',
    title: 'Thích Nghi Khắc Nghiệt',
    icon: '🏜️',
    color: 'text-emerald-400',
    badgeBorder: 'border-emerald-500',
    requiredKm: 15,
    requiredKills: 5,
    requiredChests: 5,
    requiredBadges: 50,
    passives: ['Giảm 15% tốc độ tiêu hao đói & khát', 'Tăng 10% tốc độ chạy bộ ngoài xe'],
    hpBonus: 20,
    critRateBonus: 5,
    speedBonus: 5,
    craftCritBonus: 5,
  },
  3: {
    level: 3,
    name: 'Thợ Săn Cao Tốc',
    title: 'Khắc Tinh Dã Thú',
    icon: '🏹',
    color: 'text-sky-400',
    badgeBorder: 'border-sky-500',
    requiredKm: 40,
    requiredKills: 15,
    requiredChests: 15,
    requiredBadges: 120,
    passives: ['Tăng 25% sát thương lên dã thú và cướp đường', 'Tăng 20% tỉ lệ tìm thấy rương tài nguyên quý'],
    hpBonus: 50,
    critRateBonus: 10,
    speedBonus: 10,
    craftCritBonus: 10,
  },
  4: {
    level: 4,
    name: 'Kỹ Sư Tận Thế',
    title: 'Bậc Thầy Chế Tạo & Rèn Đúc',
    icon: '⚙️',
    color: 'text-purple-400',
    badgeBorder: 'border-purple-500',
    requiredKm: 90,
    requiredKills: 30,
    requiredChests: 30,
    requiredBadges: 250,
    passives: ['Giảm 30% nguyên liệu rèn đúc', 'Thiên phú Nhập Hồn có 25% cơ hội nhân 3 sản phẩm'],
    hpBonus: 90,
    critRateBonus: 15,
    speedBonus: 15,
    craftCritBonus: 20,
  },
  5: {
    level: 5,
    name: 'Lãnh Chúa Xa Lộ',
    title: 'Bá Chủ Pháo Đài RV',
    icon: '👑',
    color: 'text-amber-400',
    badgeBorder: 'border-amber-500',
    requiredKm: 180,
    requiredKills: 60,
    requiredChests: 50,
    requiredBadges: 500,
    passives: ['Tăng 50% HP tối đa & 20 Giáp cơ bản', 'Radar quét xa tự động hút rương trong phạm vi 30m'],
    hpBonus: 150,
    critRateBonus: 25,
    speedBonus: 20,
    craftCritBonus: 30,
  },
  6: {
    level: 6,
    name: 'Bán Thần Sinh Tồn',
    title: 'Bất Tử Giữa Tận Thế',
    icon: '⚡',
    color: 'text-rose-400',
    badgeBorder: 'border-rose-500',
    requiredKm: 350,
    requiredKills: 120,
    requiredChests: 100,
    requiredBadges: 1000,
    passives: ['Hồi phục tự động 2 HP mỗi giây', 'Miễn nhiễm 100% mọi ảnh hưởng nhiệt độ thời tiết'],
    hpBonus: 250,
    critRateBonus: 35,
    speedBonus: 30,
    craftCritBonus: 40,
  },
  7: {
    level: 7,
    name: 'Thần Thoại Vô Tận',
    title: 'Chúa Tể Không Gian Xuyên Không',
    icon: '🌌',
    color: 'text-cyan-300',
    badgeBorder: 'border-cyan-400',
    requiredKm: 600,
    requiredKills: 250,
    requiredChests: 200,
    requiredBadges: 2000,
    passives: ['Tất cả chỉ số nhân đôi (200% Sức mạnh)', 'Đòn đánh phát ra lôi điện plasma hủy diệt diện rộng'],
    hpBonus: 500,
    critRateBonus: 50,
    speedBonus: 50,
    craftCritBonus: 50,
  },
};

// CÂY TRỒNG VƯỜN THỦY CANH RV
export const FARM_CROPS_CONFIG: { [id: string]: {
  id: string;
  name: string;
  icon: string;
  seedItemId: string;
  seedName: string;
  yieldItemId: string;
  yieldName: string;
  yieldQuantity: number;
  growDurationSec: number;
  waterCostLiters: number;
  requiredStageId: SurvivalStageId;
  rarity: ItemRarity;
  description: string;
  effectDescription: string;
} } = {
  crop_desert_wheat: {
    id: 'crop_desert_wheat',
    name: 'Lúa Mì Sa Mạc',
    icon: '🌾',
    seedItemId: 'seed_wheat',
    seedName: 'Hạt Giống Lúa Mì',
    yieldItemId: 'flour',
    yieldName: 'Bột Mì Thượng Hạng',
    yieldQuantity: 4,
    growDurationSec: 45,
    waterCostLiters: 2,
    requiredStageId: 'stage1_wasteland',
    rarity: 'common',
    description: 'Giống lúa mì chịu hạn cực tốt, thu hoạch để làm bánh mì bơ tuyết.',
    effectDescription: 'Thu hoạch 4x Bột mì làm thức ăn dồi dào',
  },
  crop_pure_cotton: {
    id: 'crop_pure_cotton',
    name: 'Cây Bông Tinh Khiết',
    icon: '☁️',
    seedItemId: 'seed_cotton',
    seedName: 'Hạt Giống Cây Bông',
    yieldItemId: 'cotton',
    yieldName: 'Bông Sợi Tự Nhiên',
    yieldQuantity: 5,
    growDurationSec: 60,
    waterCostLiters: 3,
    requiredStageId: 'stage2_extreme_heat',
    rarity: 'good',
    description: 'Bông sợi tự nhiên dùng may áo chống đạn Kevlar và ghế bọc da RV.',
    effectDescription: 'Thu hoạch 5x Bông sợi cho công thức áo giáp',
  },
  crop_ice_melon: {
    id: 'crop_ice_melon',
    name: 'Dưa Lưới Tuyết Băng',
    icon: '🍈',
    seedItemId: 'seed_ice_melon',
    seedName: 'Hạt Giống Dưa Tuyết',
    yieldItemId: 'ice_melon_slice',
    yieldName: 'Miếng Dưa Băng Mát Lạnh',
    yieldQuantity: 3,
    growDurationSec: 90,
    waterCostLiters: 4,
    requiredStageId: 'stage2_extreme_heat',
    rarity: 'superior',
    description: 'Trái dưa tích tụ tinh hoa tuyết băng sa mạc, ăn vào hạ nhiệt ngay lập tức.',
    effectDescription: 'Hồi 50 Khát, -3°C Thân nhiệt, +20 Tinh thần',
  },
  crop_mutant_herb: {
    id: 'crop_mutant_herb',
    name: 'Thảo Dược Đột Biến',
    icon: '🌿',
    seedItemId: 'seed_mutant_herb',
    seedName: 'Mầm Thảo Dược Đột Biến',
    yieldItemId: 'elixir_of_life',
    yieldName: 'Tinh Chất Hồi Sinh',
    yieldQuantity: 2,
    growDurationSec: 120,
    waterCostLiters: 5,
    requiredStageId: 'stage4_nightmare_spirits',
    rarity: 'perfect',
    description: 'Cỏ tiên hấp thụ linh khí quỷ dị sa mạc, hồi máu toàn diện và tăng tuổi thọ.',
    effectDescription: 'Hồi 100% HP & Giải trừ mọi độc tố',
  },
  crop_inferno_pepper: {
    id: 'crop_inferno_pepper',
    name: 'Ớt Lửa Dung Nham',
    icon: '🌶️',
    seedItemId: 'seed_inferno_pepper',
    seedName: 'Hạt Giống Ớt Hỏa Diệm',
    yieldItemId: 'inferno_spice',
    yieldName: 'Gia Vị Cuồng Nộ',
    yieldQuantity: 3,
    growDurationSec: 150,
    waterCostLiters: 6,
    requiredStageId: 'stage5_eternal_frost',
    rarity: 'epic',
    description: 'Ớt hỏa ngục tỏa nhiệt lượng xua tan giá rét -35°C, tăng 50% sát thương bạo kích.',
    effectDescription: 'Giữ ấm cơ thể trong bão tuyết & +50% Sát thương trong 10 phút',
  },
};

// 6 BẬC TIẾN HÓA CHIẾN XA RV
export const VEHICLE_TIERS_CONFIG = [
  {
    tier: 'scrap',
    name: 'Xe Van Cũ Nát',
    icon: '🚐',
    description: 'Chiếc xe cũ kỹ rỉ sét ban đầu, vừa đủ che mưa nắng hoang mạc.',
    maxSpeed: 35,
    maxFuel: 30,
    maxDurability: 100,
    radarRange: 50,
    requiredBadges: 0,
    requiredKm: 0,
    color: 'border-zinc-500 text-zinc-300',
    bonuses: ['Tốc độ tối đa 35 km/h', 'Bình xăng 30L', 'Radar cơ bản 50m'],
  },
  {
    tier: 'common',
    name: 'Xe Bán Tải Gia Cố',
    icon: '🛻',
    description: 'Được gia cố thêm khung thép chịu lực và động cơ nâng cấp.',
    maxSpeed: 55,
    maxFuel: 60,
    maxDurability: 200,
    radarRange: 120,
    requiredBadges: 100,
    requiredKm: 15,
    color: 'border-emerald-500 text-emerald-300',
    bonuses: ['Tốc độ tối đa 55 km/h', 'Bình xăng 60L', 'Mở khoang nước ngưng tụ'],
  },
  {
    tier: 'superior',
    name: 'Pháo Đài RV Sa Mạc',
    icon: '🚌',
    description: 'Biệt thự di động bọc thép, trang bị giường êm, điều hòa mát lạnh và máy làm kem.',
    maxSpeed: 80,
    maxFuel: 120,
    maxDurability: 400,
    radarRange: 250,
    requiredBadges: 300,
    requiredKm: 50,
    color: 'border-sky-500 text-sky-300',
    bonuses: ['Tốc độ 80 km/h', 'Khoang Thủy Canh Nông Trại', 'Ga tự động Cruise Control'],
  },
  {
    tier: 'rv_luxury',
    name: 'Thiết Giáp Chiến Xa Hạng Nặng',
    icon: '🛡️',
    description: 'Thiết giáp hạng nặng chống móng vuốt quái thú và đạn súng bắn tỉa của cướp đường.',
    maxSpeed: 110,
    maxFuel: 200,
    maxDurability: 750,
    radarRange: 450,
    requiredBadges: 600,
    requiredKm: 120,
    color: 'border-purple-500 text-purple-300',
    bonuses: ['Tốc độ 110 km/h', 'Nam châm hút rương tự động 30m', 'Giảm 50% va chạm hư hỏng'],
  },
  {
    tier: 'nuclear_beast',
    name: 'Chiến Xa Hạt Nhân Cyberpunk',
    icon: '🚀',
    description: 'Trang bị lò phản ứng nhiệt hạch vô tận, tháp pháo plasma tự động bắn quét quái thú.',
    maxSpeed: 150,
    maxFuel: 400,
    maxDurability: 1200,
    radarRange: 750,
    requiredBadges: 1200,
    requiredKm: 300,
    color: 'border-amber-500 text-amber-300',
    bonuses: ['Tốc độ 150 km/h', 'Tháp pháo nóc xe tự động bắn', 'Không bao giờ cạn nhiên liệu'],
  },
  {
    tier: 'celestial_carrier',
    name: 'Tàu Bay Không Gian Tinh Vân',
    icon: '🛸',
    description: 'Đỉnh cao văn minh xuyên không: Xe bay lơ lửng phản trọng lực, tiến thẳng vào thang máy vũ trụ!',
    maxSpeed: 220,
    maxFuel: 1000,
    maxDurability: 2500,
    radarRange: 1500,
    requiredBadges: 2500,
    requiredKm: 600,
    color: 'border-cyan-400 text-cyan-300',
    bonuses: ['Tốc độ 220 km/h bay lơ lửng', 'Lá chắn từ trường vô địch', 'Quét toàn bộ tài nguyên xa lộ'],
  },
];

// 4 BẬC TIẾN HÓA THẦN THÚ
export const PET_EVOLUTION_CONFIG = [
  {
    stage: 1,
    name: 'Chó Vàng Trung Hoa',
    icon: '🐕',
    rarity: 'brilliant' as ItemRarity,
    requiredLevel: 1,
    requiredExp: 0,
    abilities: ['Đánh Hơi Rương Ẩn', 'Cắn Xé Trung Thành'],
    description: 'Chú chó vàng thông minh, bạn đồng hành số 1 từ ngày đầu xuyên không.',
    atkBonus: 35,
    defBonus: 10,
  },
  {
    stage: 2,
    name: 'Thiết Giáp Khuyển Săn Thú',
    icon: '🦮',
    rarity: 'perfect' as ItemRarity,
    requiredLevel: 5,
    requiredExp: 500,
    abilities: ['Lớp Giáp Titan Phản Đòn', 'Tiếng Gầm Đe Dọa Bầy Cướp', 'Nhặt Đồ Tự Động 20m'],
    description: 'Khoác lên mình bộ giáp nhẹ titan, cắn vỡ giáp bọn cướp đường và tự gom rương.',
    atkBonus: 90,
    defBonus: 40,
  },
  {
    stage: 3,
    name: 'Lôi Điện Linh Khuyển',
    icon: '⚡🐕',
    rarity: 'epic' as ItemRarity,
    requiredLevel: 10,
    requiredExp: 1500,
    abilities: ['Lôi Điện Xung Kích', 'Mắt Thần Xuyên Màn Đêm', 'Hộ Thể Lôi Giáp Cho Chủ'],
    description: 'Tiến hóa thành linh thú sấm sét, phóng tia điện giật tê liệt toàn bộ quái vật quanh xe.',
    atkBonus: 180,
    defBonus: 80,
  },
  {
    stage: 4,
    name: 'Thần Khuyển Thao Thiết Cuồng Nộ',
    icon: '🔥🐺',
    rarity: 'brilliant' as ItemRarity,
    requiredLevel: 18,
    requiredExp: 3500,
    abilities: ['Thao Thiết Thôn Phệ Vạn Vật', 'Hào Quang Bất Tử Hồi Phục', 'Triệu Hồi Sấm Sét Huỷ Diệt'],
    description: 'Thần thú tối thượng truyền thuyết sa mạc, nuốt chửng dã thú Titan và bảo vệ chủ nhân tuyệt đối!',
    atkBonus: 380,
    defBonus: 180,
  },
];

export const INITIAL_QUESTS: Quest[] = [
  // ==========================================
  // CHƯƠNG 1: KHỞI ĐẦU HOANG MẠC & BÀN RÈN THẦN KỲ (KM 0 - 20)
  // ==========================================
  {
    id: 'q_main_1',
    chapter: 1,
    chapterName: 'Chương 1: Khởi Đầu Hoang Mạc & Bàn Rèn',
    title: 'Chương 1: Bàn Rèn Thần Kỳ & Cơn Sốt Giấy Vệ Sinh',
    type: 'main',
    description: 'Chế tạo 10 cuộn Giấy Vệ Sinh để kích hoạt thiên phú 10 Phát Nhập Hồn lần đầu tiên.',
    storyLore: 'Tuyết Mộc tỉnh giấc giữa sa mạc vô tận bên chiếc xe van cũ nát. Bàn rèn trước mặt phát ra ánh sáng tím kỳ ảo: "Phát hiện thiên phú độc quyền 10 Phát Nhập Hồn: Cứ mỗi 10 lần chế tạo, lần thứ 10 chắc chắn bạo kích thăng cấp phẩm chất!"',
    storyDialogue: [
      { speaker: 'Hệ Thống Xa Lộ', avatar: '🤖', text: '⚠️ Chào mừng 10.000 người sống sót đến với Cao Tốc Sinh Tồn! Tài nguyên ven đường có hạn, kẻ yếu sẽ bị đào thải.', role: 'system' },
      { speaker: 'Tuyết Mộc', avatar: '🧑‍🔧', text: 'Bàn rèn này... có thể chế tạo bất cứ thứ gì chỉ cần nguyên liệu thô? Thử rèn giấy vệ sinh trước xem sao!', role: 'player' },
      { speaker: 'Tinh Thần', avatar: '🥋', text: 'Này anh bạn phía trước! Tôi vừa nhặt được rương gỗ nhưng không có nước uống, anh có vật tư trao đổi không?', role: 'companion' },
    ],
    systemBroadcast: '📢 [TOÀN SERVER] Người sống sót Tuyết Mộc vừa hoàn thành chế tạo 10 cuộn Giấy Vệ Sinh, mở khóa cơn sốt giao thương đầu tiên trên Xa Lộ!',
    npcPrivateChatTrigger: {
      npcId: 'tinh_than',
      npcName: 'Tinh Thần (Nữ Hiệp Võ Thuật)',
      avatar: '🥋',
      message: 'Tuyết Mộc! Tôi vừa thấy anh rao bán giấy vệ sinh trên kênh thế giới, cho tôi đổi 1 cuộn lấy 2 chai nước tinh khiết được không?',
      autoReplyOptions: ['Được chứ Tinh Thần, ưu tiên bạn bè trước!', 'Tôi vừa gửi qua hòm thư cho cô rồi đó.'],
    },
    marketListingTrigger: {
      id: 'mkt_story_1',
      seller: 'Lý Tiểu Cường',
      sellerAvatar: '👷',
      offeredItemId: 'purified_water_500ml',
      offeredItemName: 'Nước tinh khiết 500ml',
      offeredQuantity: 3,
      offeredItemRarity: 'common',
      requestedItemId: 'toilet_paper',
      requestedItemName: 'Giấy vệ sinh',
      requestedQuantity: 2,
      isSold: false,
      isPlayerListing: false,
      tag: 'urgent',
    },
    targetCount: 10,
    currentCount: 0,
    completed: false,
    claimed: false,
    rewards: {
      badges: 30,
      diamonds: 1,
      items: [{ itemId: 'purified_water_500ml', quantity: 3 }],
      blueprintId: 'bp_bbq_skewer',
      blueprintName: 'Xiên thịt nướng sa mạc',
      title: 'Kẻ Nắm Giữ Giấy Vệ Sinh',
    },
  },
  {
    id: 'q_main_2',
    chapter: 1,
    chapterName: 'Chương 1: Khởi Đầu Hoang Mạc & Bàn Rèn',
    title: 'Chương 1: Vũ Khí Phòng Thân Cận Chiến',
    type: 'main',
    description: 'Học bản thiết kế và rèn thành công 1 thanh Dao Găm Thép hoặc Giáo Gỗ dài 2m để tự vệ trước bầy chó hoang.',
    storyLore: 'Tiếng gầm gừ của đàn chó hoang sa mạc vang vọng ngoài cửa kính xe van. Không có vũ khí tự vệ, việc bước xuống nhặt rương đồng nghĩa với tự sát.',
    storyDialogue: [
      { speaker: 'Hệ Thống Xa Lộ', avatar: '🤖', text: '⚠️ CẢNH BÁO: Phát hiện dã thú sa mạc đang lảng vảng quanh rương tài nguyên cách bạn 50m!', role: 'system' },
      { speaker: 'Tuyết Mộc', avatar: '🧑‍🔧', text: 'Dùng tấm sắt và gỗ tiêu chuẩn... Đặt lên bàn rèn. Thành công rồi, Dao Găm Thép sắc bén sáng loáng!', role: 'player' },
      { speaker: 'Trợ Lý AI', avatar: '✨', text: 'Dao găm thép có tốc độ ra đòn chớp nhoáng, nhắm thẳng điểm yếu dã thú để dứt điểm trong 1 chiêu!', role: 'system' },
    ],
    systemBroadcast: '⚔️ [HỆ THỐNG] Tuyết Mộc đã rèn thành công Vũ Khí Cận Chiến đầu tiên, sẵn sàng cho những chuyến đi săn xa lộ!',
    npcPrivateChatTrigger: {
      npcId: 'gia_chinh_kinh',
      npcName: 'Giả Chính Kinh',
      avatar: '🕵️',
      message: 'Hừ, nhặt được mấy miếng sắt vụn mà cũng đòi làm vũ khí. Đợi đấy, đội thợ săn của tôi sắp vượt qua cậu rồi!',
      autoReplyOptions: ['Cứ việc đuổi theo nếu tự tin.', 'Cẩn thận kẻo bị sói cắn rách lốp xe đấy.'],
    },
    targetCount: 1,
    currentCount: 0,
    completed: false,
    claimed: false,
    rewards: {
      badges: 40,
      diamonds: 1,
      items: [{ itemId: 'iron_plate', quantity: 10 }],
      blueprintId: 'bp_medical_kit',
      blueprintName: 'Túi cứu thương dã chiến',
      title: 'Tân Thủ Trang Bị Đầy Đủ',
    },
  },
  {
    id: 'q_main_3',
    chapter: 1,
    chapterName: 'Chương 1: Khởi Đầu Hoang Mạc & Bàn Rèn',
    title: 'Chương 1: Khai Phá Rương Tài Nguyên Ven Đường',
    type: 'main',
    description: 'Dừng xe và cạy mở thành công 3 rương tài nguyên ven đường thu thập sắt tấm, cao su và gỗ.',
    storyLore: 'Rương gỗ ven đường nằm lấp ló sau những bụi gai sa mạc. Mỗi chiếc rương là một canh bạc sinh tử giữa kho báu và cạm bẫy rình rập.',
    storyDialogue: [
      { speaker: 'Tuyết Mộc', avatar: '🧑‍🔧', text: 'Rương gỗ khóa gỉ sét... Dùng dao cạy nhẹ bản lề. Bùm! Tấm sắt, cao su và bản thiết kế lốp xe mới!', role: 'player' },
      { speaker: 'Hệ Thống Xa Lộ', avatar: '🤖', text: '🎉 Chúc mừng bạn đã hoàn thành trọn vẹn Giai Đoạn 1: Khởi Đầu Hoang Mạc!', role: 'system' },
      { speaker: 'Tinh Thần', avatar: '🥋', text: 'Tuyết Mộc ơi, phía trước đường đi nhiệt độ đang tăng vọt lên 50°C rồi, anh có nghe thấy tiếng còi cảnh báo sóng nhiệt không?', role: 'companion' },
    ],
    systemBroadcast: '🏆 [VINH DANH] Người chơi Tuyết Mộc chính thức vượt qua Giai Đoạn 1, chuẩn bị tiến vào Vùng Sóng Nhiệt 65°C!',
    npcPrivateChatTrigger: {
      npcId: 'tinh_than',
      npcName: 'Tinh Thần (Nữ Hiệp Võ Thuật)',
      avatar: '🥋',
      message: 'Tuyết Mộc ơi, đợt sóng nhiệt sắp tới nguy hiểm lắm, anh nhớ tích trữ nhiều nước ngọt nhé!',
      autoReplyOptions: ['Cảm ơn Tinh Thần, tôi đang chuẩn bị lắp máy lọc nước nóc xe.', 'Cô cũng cẩn thận nhé, đừng ra ngoài lúc giữa trưa.'],
    },
    targetCount: 3,
    currentCount: 0,
    completed: false,
    claimed: false,
    rewards: {
      badges: 50,
      diamonds: 2,
      items: [{ itemId: 'wood', quantity: 15 }],
      blueprintId: 'bp_car_tires',
      blueprintName: 'Lốp gai chống đinh',
      title: 'Kẻ Mở Rương Cần Mẫn',
    },
  },

  // ==========================================
  // CHƯƠNG 2: THỬ THÁCH NẮNG NÓNG CỰC ĐỘ (65°C) & KHỦNG HOẢNG NƯỚC (KM 20 - 50)
  // ==========================================
  {
    id: 'q_main_4',
    chapter: 2,
    chapterName: 'Chương 2: Thử Thách Nắng Nóng Cực Độ (65°C)',
    title: 'Chương 2: Cứu Tinh Nguồn Nước - Máy Ngưng Tụ Nóc Xe',
    type: 'main',
    description: 'Học và chế tạo thành công Máy Lọc Nước ngưng tụ trên nóc xe để tạo nguồn nước ổn định chống khát.',
    storyLore: 'Nhiệt độ ngoài trời tăng chóng mặt lên đến 60°C. Mặt đường nhựa bốc khói nghi ngút, người sống sót hoảng loạn vì cạn sạch nước ngọt.',
    storyDialogue: [
      { speaker: 'Hệ Thống Xa Lộ', avatar: '🤖', text: '🔥 [CẢNH BÁO KHẨN CẤP] Sóng nhiệt cực hạn 65°C đang bao trùm cao tốc! Tỷ lệ mất nước tăng gấp 3 lần.', role: 'system' },
      { speaker: 'Tuyết Mộc', avatar: '🧑‍🔧', text: 'Nếu chỉ dựa vào rương nhặt ven đường thì sẽ chết khát. Phải chế tạo Máy Ngưng Tụ Nước Nóc Xe ngay lập tức!', role: 'player' },
      { speaker: 'Tinh Thần', avatar: '🥋', text: 'Tuyết Mộc, xe của tôi cạn sạch nước làm mát két nước rồi, động cơ sắp quá nhiệt nổ tung, cứu tôi với!', role: 'companion' },
    ],
    systemBroadcast: '💧 [HỆ THỐNG] Tuyết Mộc đã chế tạo thành công Máy Ngưng Tụ Nước Nóc Xe, giải quyết khủng hoảng sinh tồn cho toàn bộ đội hình!',
    npcPrivateChatTrigger: {
      npcId: 'tinh_than',
      npcName: 'Tinh Thần (Nữ Hiệp Võ Thuật)',
      avatar: '🥋',
      message: 'Cảm ơn Tuyết Mộc! Nước mát của anh cứu mạng tôi rồi. Tôi gửi tặng anh bản thiết kế Điều Hòa Inverter tôi vừa nhặt được trong rương Bạc nhé!',
      autoReplyOptions: ['Tuyệt vời quá, đúng lúc tôi đang cần linh kiện điều hòa!', 'Giữ gìn sức khỏe nhé Tinh Thần, chúng ta cùng vượt qua đợt nóng này.'],
    },
    marketListingTrigger: {
      id: 'mkt_story_2',
      seller: 'Tô Đại Mỹ',
      sellerAvatar: '💃',
      offeredItemId: 'diamond',
      offeredItemName: 'Kim Cương Quý',
      offeredQuantity: 2,
      offeredItemRarity: 'perfect',
      requestedItemId: 'purified_water_500ml',
      requestedItemName: 'Nước tinh khiết 500ml',
      requestedQuantity: 5,
      isSold: false,
      isPlayerListing: false,
      tag: 'urgent',
    },
    targetCount: 1,
    currentCount: 0,
    completed: false,
    claimed: false,
    rewards: {
      badges: 80,
      diamonds: 2,
      items: [{ itemId: 'rubber', quantity: 12 }],
      blueprintId: 'bp_car_ac',
      blueprintName: 'Điều hòa Inverter âm trần',
      title: 'Đại Sư Nguồn Nước',
    },
  },
  {
    id: 'q_main_5',
    chapter: 2,
    chapterName: 'Chương 2: Thử Thách Nắng Nóng Cực Độ (65°C)',
    title: 'Chương 2: Ốc Đảo Di Động - Lắp Đặt Điều Hòa Inverter',
    type: 'main',
    description: 'Chế tạo và bật Điều Hòa để giảm nhiệt độ cabin xe xuống dưới 26°C, miễn nhiễm say nắng.',
    storyLore: 'Không gian trong cabin xe như một lò nướng bánh mì 50°C. Chiếc Điều Hòa Inverter chạy bằng pin mặt trời sẽ biến cabin thành ốc đảo thiên đường.',
    storyDialogue: [
      { speaker: 'Tuyết Mộc', avatar: '🧑‍🔧', text: 'Bật công tắc điều hòa Inverter... Luồng gió lạnh 22°C phả ra mát rượi! Thân nhiệt lập tức hạ về mức lý tưởng 36.8°C.', role: 'player' },
      { speaker: 'Trợ Lý AI', avatar: '✨', text: '❄️ Nhiệt độ cabin đã giảm về 22°C. Trạng thái Sốc Nhiệt được xóa bỏ hoàn toàn, tốc độ hồi phục sinh lực +40%!', role: 'system' },
      { speaker: 'Giả Chính Kinh', avatar: '🕵️', text: 'Trời ơi nóng quá! Tại sao cabin xe thằng Tuyết Mộc lại có tuyết bám trên kính thế kia?! Không thể nào!', role: 'villain' },
    ],
    systemBroadcast: '❄️ [HỆ THỐNG] Cabin xe của Tuyết Mộc đã đạt chuẩn Thiên Đường Giữa Lò Lửa (22°C), miễn nhiễm hoàn toàn hiệu ứng say nắng!',
    npcPrivateChatTrigger: {
      npcId: 'tinh_than',
      npcName: 'Tinh Thần (Nữ Hiệp Võ Thuật)',
      avatar: '🥋',
      message: 'Nghe nói xe anh mát như phòng VIP khách sạn 5 sao vậy! Sau này cho tôi ghé ké điều hòa với nha Tuyết Mộc!',
      autoReplyOptions: ['Luôn hoan nghênh cô ghé thăm!', 'Tôi vừa chế thêm tủ lạnh nữa, có cả nước đá lạnh.'],
    },
    targetCount: 1,
    currentCount: 0,
    completed: false,
    claimed: false,
    rewards: {
      badges: 100,
      diamonds: 3,
      items: [{ itemId: 'high_grade_fuel', quantity: 20 }],
      blueprintId: 'bp_car_fridge',
      blueprintName: 'Tủ lạnh xe hơi 3 ngăn',
      title: 'Thiên Đường Giữa Lò Lửa',
    },
  },
  {
    id: 'q_main_6',
    chapter: 2,
    chapterName: 'Chương 2: Thử Thách Nắng Nóng Cực Độ (65°C)',
    title: 'Chương 2: Đế Chế Băng Muối & Kem Bơ Tuyết',
    type: 'main',
    description: 'Làm thành công 10 khối Băng Muối hoặc Kem Bơ Tuyết trong tủ lạnh xe hơi để thống trị thị trường giải nhiệt.',
    storyLore: 'Tuyết Mộc phát minh ra công thức làm đá băng muối trong tủ lạnh xe hơi. Một viên đá lạnh giữa sa mạc 65°C có giá trị ngang với một thỏi vàng ròng.',
    storyDialogue: [
      { speaker: 'Tuyết Mộc', avatar: '🧑‍🔧', text: 'Muối biển + Nước tinh khiết đưa vào ngăn đông... 10 khối Băng Muối mát lạnh đã sẵn sàng! Có thể đem ra đổi lấy cả kho báu.', role: 'player' },
      { speaker: 'Giả Chính Kinh', avatar: '🕵️', text: 'Cái gì?! Hắn ta có thể sản xuất đá lạnh giữa sa mạc 65 độ sao?! Tôi trả 50 Tấm Sắt và 5 Viên Kim Cương để mua 2 khối đá!', role: 'villain' },
      { speaker: 'Hệ Thống Xa Lộ', avatar: '🤖', text: '🏆 Chúc mừng Tuyết Mộc chính thức trở thành "Vua Băng Tuyết Sa Mạc", hoàn thành xuất sắc Giai Đoạn 2!', role: 'system' },
    ],
    systemBroadcast: '🧊 [HỆ THỐNG] Tuyết Mộc chính thức đăng quang "Vua Băng Tuyết Sa Mạc", hoàn thành xuất sắc Giai Đoạn 2!',
    npcPrivateChatTrigger: {
      npcId: 'tinh_than',
      npcName: 'Tinh Thần (Nữ Hiệp Võ Thuật)',
      avatar: '🥋',
      message: 'Kem bơ tuyết anh gửi ngon tuyệt đỉnh! Ăn xong tôi cảm thấy tinh lực dồi dào, võ công tăng tiến rõ rệt luôn á!',
      autoReplyOptions: ['Ăn ngon là tốt rồi, tôi còn làm thêm cả dưa hấu ướp lạnh nữa!', 'Cố lên Tinh Thần, chúng ta sắp tới Trạm Tiếp Tế rồi.'],
    },
    targetCount: 10,
    currentCount: 0,
    completed: false,
    claimed: false,
    rewards: {
      badges: 120,
      diamonds: 3,
      blueprintId: 'bp_roof_water_tank',
      blueprintName: 'Bồn nước nóc xe 1000L',
      title: 'Vua Băng Tuyết Sa Mạc',
    },
  },

  // ==========================================
  // CHƯƠNG 3: TRẠM TIẾP TẾ & DẸP LOẠN BĂNG CƯỚP ĐƯỜNG (KM 50 - 100)
  // ==========================================
  {
    id: 'q_main_7',
    chapter: 3,
    chapterName: 'Chương 3: Trạm Tiếp Tế & Dẹp Loạn Cướp Đường',
    title: 'Chương 3: Thợ Săn Dã Thú Sa Mạc',
    type: 'main',
    description: 'Hạ gục 5 con dã thú sa mạc (Sói đói, Báo hoa, Bò cạp kim) để bảo vệ rương tài nguyên và tích lũy nanh vuốt.',
    storyLore: 'Vùng ngã rẽ xuất hiện các loài dã thú biến dị cực kỳ hung dữ. Chúng phục kích quanh các trạm dịch và rương báu.',
    storyDialogue: [
      { speaker: 'Hệ Thống Xa Lộ', avatar: '🤖', text: '🐺 [CẢNH BÁO CHIẾN ĐẤU] Phát hiện Bầy Sói Đột Biến và Bò Cạp Độc Sa Mạc đang phong tỏa lối vào Trạm Tiếp Tế!', role: 'system' },
      { speaker: 'Tuyết Mộc', avatar: '🧑‍🔧', text: 'Nỏ săn cánh đôi lắp tên thép... Bắn! Hạ gục liên tiếp 5 con dã thú, thu hoạch thịt tươi và da thuộc dẻo dai!', role: 'player' },
      { speaker: 'Trợ Lý AI', avatar: '✨', text: 'Đã thu thập đủ da thú cao cấp và nanh sói kim loại, đủ nguyên liệu để rèn áo giáp chống đạn!', role: 'system' },
    ],
    systemBroadcast: '🏹 [HỆ THỐNG] Thợ Săn Tuyết Mộc đã quét sạch dã thú sa mạc tại ngã rẽ KM 60, dọn đường cho đoàn xe!',
    npcPrivateChatTrigger: {
      npcId: 'tinh_than',
      npcName: 'Tinh Thần (Nữ Hiệp Võ Thuật)',
      avatar: '🥋',
      message: 'Tuyết Mộc cẩn thận! Tôi vừa nghe ngóng được tin Băng cướp Phi Ca đang đặt trạm kiểm soát thu phí mãi lộ ở KM 75 đấy!',
      autoReplyOptions: ['Tôi biết rồi, tôi đang chuẩn bị hỏa lực để san bằng ổ cướp này.', 'Tinh Thần giữ khoảng cách an toàn nhé, để tôi đi trước dò đường.'],
    },
    targetCount: 5,
    currentCount: 0,
    completed: false,
    claimed: false,
    rewards: {
      badges: 150,
      diamonds: 4,
      items: [{ itemId: 'bbq_meat', quantity: 10 }],
      blueprintId: 'bp_reinforced_crossbow',
      blueprintName: 'Nỏ săn cánh đôi tầm xa',
      title: 'Sát Thần Dã Thú',
    },
  },
  {
    id: 'q_main_8',
    chapter: 3,
    chapterName: 'Chương 3: Trạm Tiếp Tế & Dẹp Loạn Cướp Đường',
    title: 'Chương 3: Hỏa Lực Tuyệt Đối - Đúc Desert Eagle & Đao Đường',
    type: 'main',
    description: 'Chế tạo thành công Súng Lục Desert Eagle hoặc Đao Đường cấp Hoàn Hảo cùng 100 viên đạn AP.',
    storyLore: 'Để đối đầu với súng đạn của lũ cướp đường, Tuyết Mộc quyết định dồn toàn bộ kim cương và đồng tấm để rèn khẩu súng lục huyền thoại Desert Eagle cấp Rực Rỡ.',
    storyDialogue: [
      { speaker: 'Tuyết Mộc', avatar: '🧑‍🔧', text: 'Lần rèn thứ 10... Kích hoạt 10 Phát Nhập Hồn! Ánh sáng đỏ rực bùng lên: Desert Eagle Bạo Kích + 100 Viên Đạn Xuyên Giáp AP!', role: 'player' },
      { speaker: 'Trợ Lý AI', avatar: '✨', text: '🎯 Hỏa lực đã đạt mức tối đa. Uy lực súng đủ sức xuyên thủng kính chống đạn và giáp kim loại của xe cướp đường!', role: 'system' },
      { speaker: 'Tinh Thần', avatar: '🥋', text: 'Khẩu Desert Eagle màu bạc báng gỗ kia đẹp mê hồn luôn! Với khẩu súng này, lũ cướp Phi Ca chắc chắn phải đền tội!', role: 'companion' },
    ],
    systemBroadcast: '💥 [VŨ KHÍ THẦN THOẠI] Người chơi Tuyết Mộc đã rèn thành công Thần Binh Xa Lộ: Desert Eagle Bạo Kích Rực Rỡ!',
    npcPrivateChatTrigger: {
      npcId: 'tinh_than',
      npcName: 'Tinh Thần (Nữ Hiệp Võ Thuật)',
      avatar: '🥋',
      message: 'Tuyết Mộc ơi, súng của anh uy lực ghê thật! Tôi có nạp sẵn một hộp cứu thương đặc biệt, lát nữa chiến đấu anh nhớ mang theo nhé!',
      autoReplyOptions: ['Cảm ơn Tinh Thần, có hộp cứu thương của cô tôi càng thêm yên tâm.', 'Súng đã lên nòng, chuẩn bị xuất kích thôi!'],
    },
    targetCount: 1,
    currentCount: 0,
    completed: false,
    claimed: false,
    rewards: {
      badges: 200,
      diamonds: 5,
      items: [{ itemId: 'ammo_ap', quantity: 100 }],
      blueprintId: 'bp_ammo_ap',
      blueprintName: 'Đạn xuyên giáp AP (100 viên)',
      title: 'Thần Binh Xuất Thế',
    },
  },
  {
    id: 'q_main_9',
    chapter: 3,
    chapterName: 'Chương 3: Trạm Tiếp Tế & Dẹp Loạn Cướp Đường',
    title: 'Chương 3: Triệt Phá Băng Cướp Phi Ca & Tiếp Quản Trạm Tiếp Tế',
    type: 'main',
    description: 'Dùng súng bắn tan tác nhóm cướp có vũ khí, tiêu diệt trùm Phi Ca và tiếp quản trạm tiếp tế.',
    storyLore: 'Tên trùm Phi Ca cầm súng ngắn chặn đường trạm dịch vụ, đòi tịch thu toàn bộ xe và nước của người sống sót. Một cuộc đấu súng nghẹt thở nổ ra giữa trưa nắng.',
    storyDialogue: [
      { speaker: 'Trùm Phi Ca', avatar: '🤠', text: 'Thằng nhãi ranh đi xe cũ kia, bước xuống nộp hết nước và xăng ra đây nếu không muốn bị bắn nát gáo!', role: 'villain' },
      { speaker: 'Tuyết Mộc', avatar: '🧑‍🔧', text: 'Rút Desert Eagle... Đoàng! Một phát bắn gãy súng của Phi Ca, phát thứ hai bắn nổ bình xăng xe chỉ huy!', role: 'player' },
      { speaker: 'Hệ Thống Xa Lộ', avatar: '🤖', text: '🎖️ Băng đảng Phi Ca tan rã! Bạn đã toàn quyền tiếp quản Trạm Tiếp Tế Sa Mạc KM 80!', role: 'system' },
    ],
    systemBroadcast: '👑 [VINH QUANG TOÀN KHU VỰC] Cảnh Sát Trưởng Tuyết Mộc đã tiêu diệt băng cướp Phi Ca, giải phóng Trạm Tiếp Tế Sa Mạc!',
    npcPrivateChatTrigger: {
      npcId: 'gia_chinh_kinh',
      npcName: 'Giả Chính Kinh',
      avatar: '🕵️',
      message: 'Anh Tuyết Mộc ơi! Đại ca Tuyết Mộc ơi! Trước đây em trót dại nhiều lời, mong anh đại xá cho em vào trạm tiếp tế đổ ít xăng với ạ!',
      autoReplyOptions: ['Biết điều thì ngoan ngoãn tuân thủ luật lệ trạm tiếp tế.', 'Muốn đổi xăng thì mang kim cương và đồng tấm ra đây.'],
    },
    marketListingTrigger: {
      id: 'mkt_story_3',
      seller: 'Trạm Trưởng Dịch Vụ',
      sellerAvatar: '🎖️',
      offeredItemId: 'high_grade_fuel',
      offeredItemName: 'Xăng máy bay cao cấp 50L',
      offeredQuantity: 50,
      offeredItemRarity: 'superior',
      requestedItemId: 'ammo_ap',
      requestedItemName: 'Đạn xuyên giáp AP',
      requestedQuantity: 20,
      isSold: false,
      isPlayerListing: false,
      tag: 'rare',
    },
    targetCount: 1,
    currentCount: 0,
    completed: false,
    claimed: false,
    rewards: {
      badges: 250,
      diamonds: 6,
      blueprintId: 'bp_hunting_rifle',
      blueprintName: 'Súng trường bắn tỉa sa mạc',
      title: 'Cảnh Sát Trưởng Cao Tốc',
    },
  },

  // ==========================================
  // CHƯƠNG 4: LÊN ĐỜI XE NHÀ RV & THÚ CƯNG TRUNG HÀNH (KM 100+)
  // ==========================================
  {
    id: 'q_main_10',
    chapter: 4,
    chapterName: 'Chương 4: Lên Đời Xe Nhà RV & Thú Cưng Trung Hành',
    title: 'Chương 4: Ấp Nở & Tiến Hóa Thần Khuyển Hoàng Kim',
    type: 'main',
    description: 'Nhỏ máu nhận chủ và ấp nở thành công Chó Vàng Trung Hoa cấp Rực Rỡ để đồng hành chiến đấu.',
    storyLore: 'Quả trứng linh thú thu được từ hang ổ Boss sa mạc tỏa ra hào quang màu vàng kim ấm áp. Nhỏ một giọt máu của Tuyết Mộc, khế ước linh hồn chính thức hình thành.',
    storyDialogue: [
      { speaker: 'Tuyết Mộc', avatar: '🧑‍🔧', text: 'Nhỏ máu nhận chủ... Vỏ trứng nứt ra! Một chú Chó Vàng Trung Hoa toàn thân lấp lánh ánh kim nhảy bổ vào lòng sủa vang!', role: 'player' },
      { speaker: 'Chó Vàng Hoàng Kim', avatar: '🐕', text: 'Gâu gâu! (Chủ nhân! Con sẽ canh gác giấc ngủ cho người và nhặt sạch rương quý trên đường!)', role: 'companion' },
      { speaker: 'Trợ Lý AI', avatar: '✨', text: 'Thần Khuyển Hoàng Kim thức tỉnh 2 thiên phú: Đánh Hơi Rương Báu 300m và Cắn Xé Hộ Vệ +35 Sát thương!', role: 'system' },
    ],
    systemBroadcast: '🐾 [LINH THÚ XUẤT HIỆN] Chúc mừng Tuyết Mộc đã ấp nở thành công Thần Khuyển Hoàng Kim cấp Rực Rỡ!',
    npcPrivateChatTrigger: {
      npcId: 'tinh_than',
      npcName: 'Tinh Thần (Nữ Hiệp Võ Thuật)',
      avatar: '🥋',
      message: 'Ôi trời ơi chú chó vàng đáng yêu quá Tuyết Mộc ơi! Lông vàng óng ánh như hoàng kim luôn, cho tôi qua nựng một cái được không?',
      autoReplyOptions: ['Được chứ, chú cún này rất quấn người thân thiện!', 'Nó vừa giúp tôi tha về một chiếc rương Hoàn Hảo đấy!'],
    },
    targetCount: 1,
    currentCount: 0,
    completed: false,
    claimed: false,
    rewards: {
      badges: 200,
      diamonds: 5,
      items: [{ itemId: 'bbq_meat', quantity: 15 }],
      blueprintId: 'bp_focus_cigarette',
      blueprintName: 'Thuốc lá Tụ Thần',
      title: 'Chủ Nhân Thần Khuyển',
    },
  },
  {
    id: 'q_main_11',
    chapter: 4,
    chapterName: 'Chương 4: Lên Đời Xe Nhà RV & Thú Cưng Trung Hành',
    title: 'Chương 4: Đột Phá Xe Nhà RV Sang Trọng Tối Thượng',
    type: 'main',
    description: 'Nâng cấp toàn diện các bộ phận và hợp nhất lõi xe thành Xe Nhà RV Sang Trọng tiện nghi tối thượng.',
    storyLore: 'Hợp nhất toàn bộ khung sườn, kính cường lực, động cơ V8 và nội thất cao cấp. Chiếc xe van cũ nát biến mất, thay vào đó là một Pháo Đài RV Di Động nguy nga tráng lệ.',
    storyDialogue: [
      { speaker: 'Tuyết Mộc', avatar: '🧑‍🔧', text: 'Khởi động lõi hợp nhất... Khung xe mở rộng gấp ba! Giường ngủ nệm êm, bếp nướng, máy pha cà phê, nông trại thủy canh tự động!', role: 'player' },
      { speaker: 'Hệ Thống Xa Lộ', avatar: '🤖', text: '🏰 TIẾN HÓA HOÀN TẤT: Phương tiện của bạn đã thăng cấp lên: Xe Nhà RV Sang Trọng (Cấp 4) - Tốc độ 120km/h, Giáp hợp kim 500HP!', role: 'system' },
      { speaker: 'Trợ Lý AI', avatar: '✨', text: 'Đã kích hoạt khoang Thủy Canh Nông Trại RV! Bạn có thể gieo trồng Lúa Mì, Cây Bông và Dưa Tuyết trong buồng sinh thái.', role: 'system' },
    ],
    systemBroadcast: '🚀 [CHÚA TỂ CAO TỐC] Tuyết Mộc đã sở hữu Xe Nhà RV Sang Trọng Đệ Nhất Xa Lộ, trở thành huyền thoại bất tử của 10.000 người sống sót!',
    npcPrivateChatTrigger: {
      npcId: 'tinh_than',
      npcName: 'Tinh Thần (Nữ Hiệp Võ Thuật)',
      avatar: '🥋',
      message: 'Xe RV của anh nhìn qua kính viễn vọng đẹp lộng lẫy như một khách sạn 5 sao di động vậy! Chúc mừng Tuyết Mộc nhé!',
      autoReplyOptions: ['Cảm ơn Tinh Thần, bao giờ rảnh ghé xe tôi nếm thử cà phê và kem tuyết nhé!', 'Chúng ta đã tiến rất xa so với ngày đầu rồi.'],
    },
    targetCount: 1,
    currentCount: 0,
    completed: false,
    claimed: false,
    rewards: {
      badges: 400,
      diamonds: 10,
      blueprintId: 'bp_ice_cream_maker',
      blueprintName: 'Máy làm kem bơ tuyết',
      title: 'Chúa Tể Đường Cao Tốc',
    },
  },
  {
    id: 'q_main_12',
    chapter: 4,
    chapterName: 'Chương 4: Lên Đời Xe Nhà RV & Thú Cưng Trung Hành',
    title: 'Chương 4: Nhẫn Trữ Vật Không Gian & Radar Toàn Cảnh 1000M',
    type: 'main',
    description: 'Chế tạo hoặc trang bị Nhẫn Trữ Vật Không Gian 100m³ và Hệ Thống Radar Quét Rương 1000M.',
    storyLore: 'Với Nhẫn Trữ Vật Không Gian 100m³ trên ngón tay và Radar lượng tử 1000m trên nóc RV, Tuyết Mộc đã làm chủ hoàn toàn không gian và thời gian trên Xa Lộ Sinh Tồn.',
    storyDialogue: [
      { speaker: 'Tuyết Mộc', avatar: '🧑‍🔧', text: 'Thu toàn bộ rương gỗ, xăng dầu, đạn dược vào nhẫn không gian... Khoang xe rộng thênh thang như một căn biệt thự!', role: 'player' },
      { speaker: 'Trợ Lý AI', avatar: '✨', text: '📡 Radar đã quét toàn bộ xa lộ trong bán kính 1000m. Mọi rương Kim Cương và mỏ tài nguyên đều hiển thị trên bản đồ số!', role: 'system' },
      { speaker: 'Hệ Thống Xa Lộ', avatar: '🤖', text: '🏆 ĐẠI THÀNH TỰU: Tuyết Mộc đã hoàn thành xuất sắc 4 Chương Cốt Truyện Chính! Bạn là Vị Vua Không Ngai của Highway Survival!', role: 'system' },
    ],
    systemBroadcast: '👑 [HÀO QUANG VĨNH CỬU] Chúc mừng Tuyết Mộc đã hoàn thành xuất sắc toàn bộ 4 Giai Đoạn Cốt Truyện của Highway Survival RPG!',
    npcPrivateChatTrigger: {
      npcId: 'tinh_than',
      npcName: 'Tinh Thần (Nữ Hiệp Võ Thuật)',
      avatar: '🥋',
      message: 'Tuyết Mộc, chúng ta đã cùng nhau vượt qua cả 4 chặng đường sinh tử. Cảm ơn anh đã luôn đồng hành và bảo vệ tôi suốt hành trình này!',
      autoReplyOptions: ['Được đồng hành cùng cô là niềm vinh hạnh của tôi.', 'Hành trình xa lộ vẫn còn dài, chúng ta sẽ tiếp tục tiến bước!'],
    },
    targetCount: 1,
    currentCount: 0,
    completed: false,
    claimed: false,
    rewards: {
      badges: 500,
      diamonds: 15,
      blueprintId: 'bp_radar_scanner',
      blueprintName: 'Hệ thống Radar quét rương 1000M',
      title: 'Bàn Tay Nắm Cả Càn Khôn',
    },
  },

  // ==========================================
  // THỬ THÁCH HẰNG NGÀY (DAILY BOUNTIES)
  // ==========================================
  {
    id: 'q_daily_1',
    title: 'Thử Thách Ngày: Hành Trình Vạn Dặm',
    type: 'daily',
    description: 'Lái xe vượt qua quãng đường 25 km trên cao tốc.',
    targetCount: 25,
    currentCount: 0,
    completed: false,
    claimed: false,
    rewards: { badges: 35, diamonds: 1, items: [{ itemId: 'high_grade_fuel', quantity: 20 }] },
  },
  {
    id: 'q_daily_2',
    title: 'Thử Thách Ngày: Bàn Rèn Rực Lửa',
    type: 'daily',
    description: 'Chế tạo tổng cộng 12 món đồ bất kỳ tại Bàn Rèn Thần Kỳ.',
    targetCount: 12,
    currentCount: 0,
    completed: false,
    claimed: false,
    rewards: { badges: 40, diamonds: 1, items: [{ itemId: 'iron_plate', quantity: 15 }] },
  },
  {
    id: 'q_daily_3',
    title: 'Thử Thách Ngày: Giao Thương Kênh Thế Giới',
    type: 'daily',
    description: 'Hoàn thành 2 phiên mua/bán trên Chợ Giao Dịch hoặc gửi tin nhắn giao lưu với Tinh Thần.',
    targetCount: 2,
    currentCount: 0,
    completed: false,
    claimed: false,
    rewards: { badges: 30, diamonds: 1 },
  },
  {
    id: 'q_daily_4',
    title: 'Thử Thách Ngày: Săn Bắn Dã Ngoại',
    type: 'daily',
    description: 'Hạ gục 3 con dã thú sa mạc và thu hoạch thịt.',
    targetCount: 3,
    currentCount: 0,
    completed: false,
    claimed: false,
    rewards: { badges: 45, diamonds: 1, items: [{ itemId: 'salt', quantity: 5 }] },
  },
  {
    id: 'q_daily_5',
    title: 'Thử Thách Ngày: Bồi Bổ Thần Khuyển',
    type: 'daily',
    description: 'Cho Chó Vàng ăn 3 miếng thịt tươi để tăng cấp và lực chiến.',
    targetCount: 3,
    currentCount: 0,
    completed: false,
    claimed: false,
    rewards: { badges: 35, items: [{ itemId: 'purified_water_500ml', quantity: 2 }] },
  },
  {
    id: 'q_daily_6',
    title: 'Thử Thách Ngày: Chế Tạo Đạn Dược',
    type: 'daily',
    description: 'Rèn 50 viên đạn súng để chuẩn bị sẵn sàng hỏa lực.',
    targetCount: 50,
    currentCount: 0,
    completed: false,
    claimed: false,
    rewards: { badges: 50, diamonds: 2 },
  },

  // ==========================================
  // NHIỆM VỤ ẨN (HIDDEN & LEGENDARY QUESTS)
  // ==========================================
  {
    id: 'q_hidden_1',
    title: 'Nhiệm Vụ Ẩn: Trùm Tài Phiệt Băng Muối',
    type: 'hidden',
    description: 'Chế tạo 20 phần Băng Muối trong đợt nắng nóng cực độ để thống trị nguồn nước sinh tồn.',
    targetCount: 20,
    currentCount: 0,
    completed: false,
    claimed: false,
    rewards: { badges: 150, diamonds: 5, title: 'Thần Tài Băng Muối' },
  },
  {
    id: 'q_hidden_2',
    title: 'Nhiệm Vụ Ẩn: Dẹp Loạn Cướp Đường',
    type: 'hidden',
    description: 'Bắn hạ tên trùm cầm súng Phi Ca và tịch thu toàn bộ kho xăng dầu tiếp tế.',
    targetCount: 1,
    currentCount: 0,
    completed: false,
    claimed: false,
    rewards: { badges: 250, diamonds: 8, title: 'Bách Phát Bách Trúng' },
  },
  {
    id: 'q_hidden_3',
    title: 'Nhiệm Vụ Ẩn: Bí Mật Giả Chính Kinh',
    type: 'hidden',
    description: 'Lật tẩy trò bịp bợm và thu mua toàn bộ vật tư giá rẻ trên kênh thế giới.',
    targetCount: 5,
    currentCount: 0,
    completed: false,
    claimed: false,
    rewards: { badges: 180, diamonds: 4, title: 'Nhìn Thấu Hồng Trần' },
  },
  {
    id: 'q_hidden_4',
    title: 'Nhiệm Vụ Ẩn: Đại Sư Rèn 100 Phát',
    type: 'hidden',
    description: 'Kích hoạt thiên phú 10 Phát Nhập Hồn tổng cộng 10 lần (đạt 100 lần rèn).',
    targetCount: 10,
    currentCount: 0,
    completed: false,
    claimed: false,
    rewards: { badges: 300, diamonds: 10, title: 'Thần Thợ Rèn Tuyết Mộc' },
  },
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach_first_craft',
    title: 'Bàn Tay Thợ Rèn',
    description: 'Lần đầu tiên hoàn thành chế tạo tại Bàn Rèn.',
    icon: '🔨',
    unlocked: false,
    rewardBadges: 15,
    rewardDiamonds: 1,
  },
  {
    id: 'ach_soul_infusion',
    title: '10 Phát Nhập Hồn!',
    description: 'Kích hoạt thành công thiên phú bạo kích thăng phẩm chất lần thứ 10.',
    icon: '✨',
    unlocked: false,
    rewardBadges: 50,
    rewardDiamonds: 2,
  },
  {
    id: 'ach_first_blueprint',
    title: 'Nhà Nghiên Cứu Kỹ Thuật',
    description: 'Học và mở khóa thành công bản thiết kế đầu tiên nhặt được từ rương.',
    icon: '📜',
    unlocked: false,
    rewardBadges: 40,
    rewardDiamonds: 2,
  },
  {
    id: 'ach_pet_hatched',
    title: 'Bạn Đồng Hành Trung Thành',
    description: 'Ấp nở thành công Chó Vàng Trung Hoa cấp Rực Rỡ.',
    icon: '🐕',
    unlocked: false,
    rewardBadges: 80,
    rewardDiamonds: 3,
  },
  {
    id: 'ach_rv_master',
    title: 'Dinh Thự Di Động',
    description: 'Nâng cấp chiếc xe van nát thành Xe Nhà RV sang trọng.',
    icon: '🚐',
    unlocked: false,
    rewardBadges: 150,
    rewardDiamonds: 5,
  },
  {
    id: 'ach_tinh_than_ally',
    title: 'Hồng Nhan Tri Kỷ',
    description: 'Trao đổi vũ khí và vật phẩm quan trọng với nữ hiệp Tinh Thần.',
    icon: '❤️',
    unlocked: false,
    rewardBadges: 60,
    rewardDiamonds: 2,
  },
  {
    id: 'ach_space_ring',
    title: 'Bàn Tay Nắm Cả Không Gian',
    description: 'Nhỏ máu nhận chủ Nhẫn Trữ Vật cấp Sử Thi 100m³.',
    icon: '💍',
    unlocked: false,
    rewardBadges: 100,
    rewardDiamonds: 4,
  },
  {
    id: 'ach_marksman',
    title: 'Xạ Thủ Bất Bại',
    description: 'Bắn hạ 10 dã thú hoặc cướp đường bằng Desert Eagle hoặc súng trường.',
    icon: '🎯',
    unlocked: false,
    rewardBadges: 120,
    rewardDiamonds: 5,
  },
];

export const RARITY_SORT_WEIGHT: Record<string, number> = {
  brilliant: 5,
  epic: 4,
  perfect: 4,
  superior: 3,
  good: 2,
  rare: 2,
  common: 1,
};

export function resolveItemInfo(itemId: string, fallbackRarity: ItemRarity = 'common'): { name: string; icon: string; rarity: ItemRarity } {
  // 1. Check if it's a blueprint
  if (itemId.startsWith('blueprint_') || itemId.startsWith('bp_')) {
    const bpId = itemId.replace('blueprint_', '');
    const bp = INITIAL_BLUEPRINTS.find((b) => b.id === bpId || b.id === itemId);
    if (bp) {
      return {
        name: `Bản Thiết Kế: ${bp.name}`,
        icon: '📜',
        rarity: bp.rarity || fallbackRarity,
      };
    }
    return {
      name: `Bản Thiết Kế: ${bpId.replace('bp_', '')}`,
      icon: '📜',
      rarity: fallbackRarity || 'superior',
    };
  }

  // 2. Check initial items
  const found = INITIAL_ITEMS.find((i) => i.id === itemId);
  if (found) {
    return {
      name: found.name,
      icon: found.icon,
      rarity: found.rarity || fallbackRarity,
    };
  }

  // 3. Known specific items dictionary
  const KNOWN_MAP: Record<string, { name: string; icon: string; rarity: ItemRarity }> = {
    diamond: { name: 'Kim cương nguyên khối', icon: '💎', rarity: 'brilliant' },
    space_crystal: { name: 'Tinh thể không gian', icon: '🔮', rarity: 'epic' },
    high_grade_fuel: { name: 'Xăng máy bay cao cấp', icon: '⛽', rarity: 'perfect' },
    gunpowder: { name: 'Thuốc súng cao cấp', icon: '🧨', rarity: 'superior' },
    copper_plate: { name: 'Tấm đồng tinh luyện', icon: '🟨', rarity: 'superior' },
    iron_plate: { name: 'Tấm sắt tiêu chuẩn', icon: '🔩', rarity: 'common' },
    rubber: { name: 'Miếng cao su', icon: '⬛', rarity: 'common' },
    wood: { name: 'Khối gỗ tiêu chuẩn', icon: '🪵', rarity: 'common' },
    bread: { name: 'Bánh mì dinh dưỡng', icon: '🍞', rarity: 'common' },
    salt: { name: 'Muối ăn hạt to', icon: '🧂', rarity: 'common' },
    purified_water_500ml: { name: 'Nước tinh khiết 500ml', icon: '💧', rarity: 'common' },
    snake_meat: { name: 'Thịt rắn sa mạc', icon: '🥩', rarity: 'common' },
    mouse_meat: { name: 'Thịt chuột đồng', icon: '🥩', rarity: 'common' },
    cat_meat: { name: 'Thịt mèo hoang', icon: '🥩', rarity: 'common' },
    wolf_meat: { name: 'Thịt sói hoang (500g)', icon: '🥩', rarity: 'good' },
    bear_meat: { name: 'Thịt gấu đêm thượng hạng', icon: '🥩', rarity: 'epic' },
    tiger_meat: { name: 'Thịt hổ bạo kích', icon: '🥩', rarity: 'brilliant' },
    lion_meat: { name: 'Thịt sư tử sa mạc chúa', icon: '🥩', rarity: 'brilliant' },
    rhino_meat: { name: 'Thịt tê giác bọc giáp', icon: '🥩', rarity: 'brilliant' },
    scorpion_meat: { name: 'Thịt bọ cạp độc', icon: '🦂', rarity: 'superior' },
    ice_salt: { name: 'Băng Muối Giải Nhiệt (50ml)', icon: '🧊', rarity: 'perfect' },
    ice_cream: { name: 'Kem Bơ Tuyết Ướp Lạnh', icon: '🍦', rarity: 'brilliant' },
    seed_wheat: { name: 'Hạt giống lúa mì', icon: '🌱', rarity: 'common' },
    seed_cotton: { name: 'Hạt giống cây bông', icon: '🌾', rarity: 'good' },
    seed_ice_melon: { name: 'Hạt giống dưa tuyết', icon: '🍈', rarity: 'superior' },
    seed_mutant_herb: { name: 'Mầm thảo dược đột biến', icon: '🌿', rarity: 'perfect' },
    seed_inferno_pepper: { name: 'Hạt ớt hỏa diệm', icon: '🌶️', rarity: 'epic' },
    flour: { name: 'Bột mì thượng hạng', icon: '🌾', rarity: 'common' },
    cotton: { name: 'Bông sợi tự nhiên', icon: '☁️', rarity: 'good' },
    ice_melon_slice: { name: 'Miếng dưa băng mát lạnh', icon: '🍉', rarity: 'superior' },
    elixir_of_life: { name: 'Tinh chất hồi sinh', icon: '🧪', rarity: 'perfect' },
    meat: { name: 'Thịt thú tươi', icon: '🥩', rarity: 'common' },
    buffalo_meat: { name: 'Thịt trâu rừng thiết giáp', icon: '🥩', rarity: 'superior' },
    leopard_meat: { name: 'Thịt báo hoa sa mạc', icon: '🥩', rarity: 'good' },
    bear_paw: { name: 'Bàn tay gấu hầm dinh dưỡng', icon: '🐾', rarity: 'epic' },
    tiger_bone_powder: { name: 'Bột cao xương hổ bạo kích', icon: '✨', rarity: 'brilliant' },
    special_crystal: { name: 'Tinh thể nguyên tố đặc biệt', icon: '💠', rarity: 'brilliant' },
    titanium_alloy: { name: 'Hợp kim titan siêu cứng', icon: '🛡️', rarity: 'brilliant' },
    electronic_chip: { name: 'Vi mạch điện tử cơ giáp', icon: '💽', rarity: 'superior' },
    ammo_standard: { name: 'Hộp đạn tiêu chuẩn 9mm', icon: '💥', rarity: 'good' },
    ammo_ap: { name: 'Đạn xuyên giáp AP Armor-Piercing', icon: '💥', rarity: 'superior' },
    cosmic_core: { name: 'Lõi Năng Lượng Không Gian', icon: '🪐', rarity: 'brilliant' },
  };

  if (KNOWN_MAP[itemId]) {
    return KNOWN_MAP[itemId];
  }

  return {
    name: itemId,
    icon: '📦',
    rarity: fallbackRarity,
  };
}

